version: '3.8'
services:
    mongo:
        image: mongo:4.4.5
        volumes:
            - /data/db:/data/db
        ports:
            - 27017:27017
    frontend:
        build: .\diabetedetectorui\Dockerfile
        image: frontend
        ports:
            - 5002:80/tcp
    patient:
        build: .\patient\Dockerfile
        image: patient
        ports:
            - 8081:8081
    report:
        build: .\report\Dockerfile
        image: report
        ports:
            - 8080:8080
    history:
        build: .\history\Dockerfile
        image: history
        ports:
            - 8082:8082
        depends_on:
            - mongo
    